: MAIN
  ( cover required core/runtime words )
  S"TOKENS:(" PWRITE-STR PWRITELN

  3 4 + PWRITE-I32 PWRITELN
  9 2 - PWRITE-I32 PWRITELN
  6 7 * PWRITE-I32 PWRITELN
  7 3 / PWRITE-I32 PWRITELN
  7 3 MOD PWRITE-I32 PWRITELN

  5 NEGATE PWRITE-I32 PWRITELN
  -1 -1 AND PWRITE-BOOL PWRITELN

  0 0= PWRITE-BOOL PWRITELN
  -1 0< PWRITE-BOOL PWRITELN
  5 5 = PWRITE-BOOL PWRITELN
  5 6 <> PWRITE-BOOL PWRITELN
  3 4 < PWRITE-BOOL PWRITELN
  3 3 <= PWRITE-BOOL PWRITELN
  4 3 > PWRITE-BOOL PWRITELN
  4 4 >= PWRITE-BOOL PWRITELN

  1 IF
    S"IF-TRUE" PWRITE-STR
  ELSE
    S"IF-FALSE" PWRITE-STR
  THEN
  PWRITELN

  0 IF
    S"ELSE-FALSE" PWRITE-STR
  ELSE
    S"ELSE-TRUE" PWRITE-STR
  THEN
  PWRITELN

  3 BEGIN
    DUP 0= 0= WHILE
      DUP PWRITE-I32 PWRITELN
      1 -
  REPEAT
  DROP

  0 BEGIN
    1 + DUP 3 >=
  UNTIL
  PWRITE-I32 PWRITELN

  5 >R
  R@ PWRITE-I32 PWRITELN
  R> PWRITE-I32 PWRITELN

  10 CONSTANT TEN
  TEN PWRITE-I32 PWRITELN

  CREATE BUF
  65 ,
  66 ,
  2 ALLOT
  BUF PWRITE-I32 PWRITELN

  123 7 PVAR!
  7 PVAR@ PWRITE-I32 PWRITELN

  9 1 2 PFIELD!
  1 2 PFIELD@ PWRITE-I32 PWRITELN

  123 PBOOL PWRITE-BOOL PWRITELN

  65 PWRITE-CHAR PWRITELN
  255 PWRITE-HEX PWRITELN

  PREAD-I32 PWRITE-I32 PWRITELN
  PREADLN
  PREAD-BOOL PWRITE-BOOL PWRITELN
  PREADLN
  PREAD-CHAR PWRITE-CHAR PWRITELN
  PREADLN
;
